{{- if eq .Values.cloudProvider "azure" }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: grafana-agent
  labels:
    {{- include "grafana-agent-extras.labels" . | nindent 4 }}
spec:
  type: 0
  resourceID: {{ .Values.azureConfig.resourceID }}
  clientID: {{ .Values.azureConfig.clientID }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: grafana-agent
spec:
  azureIdentity: grafana-agent
  selector: grafana-agent
{{- end }}
