apiVersion: v1
kind: Secret
metadata:
  name: primary-credentials-logs
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.remote.logs.username }}
  password: {{ .Values.remote.logs.password }}