kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-agent-traces
  namespace: {{ .Release.Namespace }}
data:
  agent.yaml: |
    server:
      log_level: debug
    tempo:
      configs:
        - name: default
          remote_write:
            - endpoint: ${TRACES_REMOTE_WRITE_URL}
              basic_auth:
                username: ${TRACES_USERNAME}
                password: ${TRACES_PASSWORD}
          receivers:
            otlp:
              protocols:
                http: {}
                grpc: {}
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:55678
