apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: grafana-agent-traces
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: grafana-agent-traces
  template:
    metadata:
      labels:
        name: grafana-agent-traces
    spec:
      priorityClassName: "platform-medium"
      containers:
        - args:
            - -config.file=/etc/agent/agent.yaml
            - -config.expand-env
          command:
            - /bin/agent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TRACES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecretName }}
                  key: traces_username
            - name: TRACES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecretName }}
                  key: traces_password
            - name: TRACES_REMOTE_WRITE_URL
              value: {{ .Values.remote.tracesUrl | quote }}
          image: grafana/agent:v0.21.2
          imagePullPolicy: IfNotPresent
          name: agent
          ports:
            - containerPort: 8080
              name: http-metrics
            - containerPort: 4318
              name: otlp-http
              protocol: TCP
            - containerPort: 4317
              name: otlp-grpc
              protocol: TCP
            - containerPort: 55681
              name: otlp-legacy
              protocol: TCP
            - containerPort: 55678
              name: jaeger
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/agent
              name: grafana-agent-traces
          resources:
            requests:
              cpu: {{ .Values.traces.resources.requests.cpu }}
              memory: {{ .Values.traces.resources.requests.memory }}
      serviceAccount: grafana-agent
      volumes:
        - configMap:
            name: grafana-agent-traces
          name: grafana-agent-traces
