apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: platform-high
  labels:
    {{- include "aks-core-extras.labels" . | nindent 4 }}
    "xkf.xenit.io/kind": "platform"
description: "Used by DaemonSets that need to always schedule on every node. Ex. node-exporter, promtail, aad-pod-identity-nmi."
value:  900002
preemptionPolicy: PreemptLowerPriority
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: platform-medium
  labels:
    "xkf.xenit.io/kind": "platform"
    {{- include "aks-core-extras.labels" . | nindent 4 }}
description: "Used by less critical pods that still need premeption. Ex. Thanos Receiver, Nginx Ingress."
value: 900001
preemptionPolicy: Never
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: platform-low
  labels:
    "xkf.xenit.io/kind": "platform"
    {{- include "aks-core-extras.labels" . | nindent 4 }}
description: "Should be default for all other platform pods."
value: 900000
preemptionPolicy: Never
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: tenant-high
  labels:
    "xkf.xenit.io/kind": "tenant"
    {{- include "aks-core-extras.labels" . | nindent 4 }}
description: "Used by tenant critical applications that needs to run."
value: 800002
preemptionPolicy: Never
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: tenant-medium
  labels:
    "xkf.xenit.io/kind": "tenant"
    {{- include "aks-core-extras.labels" . | nindent 4 }}
description: "Used by less critical tenant applications that still need priority."
value: 800001
preemptionPolicy: Never
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: tenant-low
  labels:
    "xkf.xenit.io/kind": "tenant"
    {{- include "aks-core-extras.labels" . | nindent 4 }}
description: "Good default for most tenant pods."
value: 800000
preemptionPolicy: Never
globalDefault: false
