apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: aad-pod-identity-mic
  namespace: aad-pod-identity
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: aad-pod-identity
      app.kubernetes.io/name: aad-pod-identity
      app.kubernetes.io/component: mic
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: aad-pod-identity-nmi
  namespace: aad-pod-identity
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: aad-pod-identity
      app.kubernetes.io/name: aad-pod-identity
      app.kubernetes.io/component: nmi
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    xkf.xenit.io/monitoring: platform
  name: cert-manager
  namespace: cert-manager
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    scrapeTimeout: 30s
    targetPort: 9402
  jobLabel: cert-manager
  namespaceSelector:
    matchNames:
    - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: cert-manager
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: secrets-store-csi-driver
  namespace: csi-secrets-store-provider-azure
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secrets-store-csi-driver
      app.kubernetes.io/instance: csi-secrets-store-provider-azure
  podMetricsEndpoints:
    - path: /metrics
      port: "8081"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    xkf.xenit.io/monitoring: platform
  name: external-dns
  namespace: external-dns
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - external-dns
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-dns
      app.kubernetes.io/name: external-dns
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: helm-controller
  namespace: flux-system
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app: helm-controller
  podMetricsEndpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kustomize-controller
  namespace: flux-system
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  podMetricsEndpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: notification-controller
  namespace: flux-system
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app: notification-controller
  podMetricsEndpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: source-controller
  namespace: flux-system
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app: source-controller
  podMetricsEndpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: azdo-proxy
  namespace: flux-system
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: azdo-proxy
      app.kubernetes.io/name: azdo-proxy
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    xkf.xenit.io/monitoring: platform
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    xkf.xenit.io/monitoring: platform
  name: falco-exporter
  namespace: falco
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - falco
  selector:
    matchLabels:
      app.kubernetes.io/instance: falco-exporter
      app.kubernetes.io/name: falco-exporter
{{- if .Values.enabledMonitors.opaGatekeeper }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gatekeeper-audit
  namespace: gatekeeper-system
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app: gatekeeper
      control-plane: audit-controller
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gatekeeper-controller-manager
  namespace: gatekeeper-system
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app: gatekeeper
      control-plane: controller-manager
  podMetricsEndpoints:
    - port: metrics
{{- end }}
{{- if .Values.enabledMonitors.linkerd }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linkerd-federate
  namespace: linkerd-viz
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    params:
      match[]:
      - '{job="linkerd-proxy"}'
      - '{job="linkerd-controller"}'
    path: /federate
    port: admin-http
    honorLabels: true
    relabelings:
    - action: keep
      regex: '^prometheus$'
      sourceLabels:
      - '__meta_kubernetes_pod_container_name'
  jobLabel: app
  namespaceSelector:
    matchNames:
    - linkerd-viz
  selector:
    matchLabels:
      component: prometheus
{{- end }}
{{- if .Values.enabledMonitors.goldpinger }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goldpinger
  namespace: goldpinger
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  endpoints:
  - interval: 30s
    port: http
  namespaceSelector:
    matchNames:
    - goldpinger
  selector:
    matchLabels:
      app.kubernetes.io/instance: goldpinger
      app.kubernetes.io/name: goldpinger
{{- end }}
