{{ if and .Values.resourceID .Values.clientID }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: external-dns
spec:
  type: 0
  resourceID: {{ .Values.resourceID }}
  clientID: {{ .Values.clientID }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: external-dns
spec:
  azureIdentity: external-dns
  selector: external-dns
{{ end }}
