{{ if and .Values.resourceID .Values.clientID }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: azure-metrics
spec:
  type: 0
  resourceID: {{ .Values.resourceID }}
  clientID: {{ .Values.clientID }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: azure-metrics
spec:
  azureIdentity: azure-metrics
  selector: azure-metrics
{{ end }}
