apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: popeye
  labels:
    xkf.xenit.io/kind: "platform"
subjects:
  - kind: ServiceAccount
    name: popeye
    namespace: popeye
roleRef:
  kind: ClusterRole
  name: popeye
  apiGroup: rbac.authorization.k8s.io