apiVersion: v1
kind: Secret
metadata:
  name: popeye-secret
  namespace:  popeye
  labels:
    xkf.xenit.io/kind: "platform"
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azure.storageAccount.name | b64enc }}
  azurestorageaccountkey: {{ .Values.azure.storageAccount.key | b64enc }}