apiVersion: v1
kind: ServiceAccount
metadata:
  name: popeye
  namespace: popeye
  labels:
    xkf.xenit.io/kind: "platform"
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity.id }}