version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "opentofu"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
