version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/azure"
    schedule:
      interval: "daily"
  - package-ecosystem: "opentofu"
    directory: "/modules/kubernetes/"
    schedule:
      interval: "daily"
