nameOverride: ""
fullnameOverride: ""

cloudProvider: ""
secretName: "xenit-proxy-certificate"

azureConfig:
  resourceID: ""
  clientID: ""
  tenantID: ""
  keyVaultName: ""
  keyVaultSecretName: "xenit-proxy-certificate"

awsConfig:
  keyParameterName: "xenit-proxy-certificate-key"
  crtParameterName: "xenit-proxy-certificate-crt"
