nameOverride: ""
fullnameOverride: ""

cloudProvider: ""

azureConfig:
  resourceID: ""
  clientID: ""
  tenantID: ""
  keyVaultName: ""
  keyVaultSecretName: "xenit-proxy-certificate"

awsConfig:
  parameterName: "xenit-proxy-certificate"
