apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  clusterName: {{ .Values.clusterName }}
  site: {{ .Values.site }}
  credentials:
    apiSecret:
      secretName: datadog-operator-apikey
      keyName: api-key
    appSecret:
      secretName: datadog-operator-appkey
      keyName: app-key
  agent:
    priorityClassName: platform-high
    image:
      name: "gcr.io/datadoghq/agent:latest"
    log:
      enabled: true
      logsConfigContainerCollectAll: true
    apm:
      enabled: true
      hostPort: 8126
    env:
      - name: DD_CONTAINER_EXCLUDE_LOGS
        value: "name:datadog-agent"
      - name: DD_CONTAINER_INCLUDE
        value: {{ .Values.containerInclude }}
      - name: DD_CONTAINER_EXCLUDE
        value: "kube_namespace:.*"
    config:
      tags:
        - env:{{ .Values.environment }}
      kubelet:
        tlsVerify: false
      criSocket:
        criSocketPath: /var/run/containerd/containerd.sock
      volumeMounts:
        - name: containerdsocket
          mountPath: /var/run/containerd/containerd.sock
      volumes:
        - hostPath:
            path: /var/run/containerd/containerd.sock
          name: containerdsocket
        - hostPath:
            path: /var/run
          name: var-run
  clusterAgent:
    replicas: 2
    priorityClassName: platform-low
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
  features:
    kubeStateMetricsCore:
      enabled: true
    logCollection:
      enabled: true
      logsConfigContainerCollectAll: true
