# Default values for csi-secrets-store-provider-aws.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.r2-6-gee95299-2022.04.14.21.07"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
