{{- if .Values.defaultCertificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx
spec:
  dnsNames:
    - '*.{{ .Values.defaultCertificate.dnsZone }}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: ingress-nginx
{{- end }}
