{{- if .Values.defaultCertificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx
spec:
  secretName: ingress-nginx
  revisionHistoryLimit: 3
  dnsNames:
    - '*.{{ .Values.defaultCertificate.dnsZone }}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
{{- end }}
