---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: ${name}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux
  namespace: ${name}
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux
  namespace: ${name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux
subjects:
- kind: ServiceAccount
  name: flux
  namespace: ${name}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ${name}
  namespace: ${name}
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux
  url: ssh://git@github.com/${github_owner}/${name}.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ${name}
  namespace: ${name}
spec:
  serviceAccountName: flux
  interval: 1m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${name}
    namespace: flux-system
  validation: client
