{{ if and .Values.resourceID .Values.clientID }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: trivy
spec:
  type: 0
  resourceID: {{ .Values.resourceID }}
  clientID: {{ .Values.clientID }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: trivy
spec:
  azureIdentity: trivy
  selector: trivy
{{ end }}
