---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: ${azdo_repo}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux
  namespace: ${azdo_repo}
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux
  namespace: ${azdo_repo}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux
subjects:
- kind: ServiceAccount
  name: flux
  namespace: ${azdo_repo}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ${azdo_repo}
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: http://git-cache-http-server/dev.azure.com/${azdo_org}/${azdo_proj}/_git/${azdo_repo}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ${azdo_repo}
  namespace: ${azdo_repo}
spec:
  serviceAccountName: flux
  interval: 1m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${azdo_repo}
    namespace: flux-system
  validation: client
