apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-security-context
spec:
  validationFailureAction: enforce
  rules:
    - name: set-security-context
      match:
        resources:
          kinds:
            - Pod
          namespaces: {{ .Values.namespaces }}
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - NET_RAW
