apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: vector
spec:
  type: 0
  resourceID: {{ .Values.azureConfig.resourceID }}
  clientID: {{ .Values.azureConfig.clientID }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: vector
spec:
  azureIdentity: vector
  selector: vector
