apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vector
spec:
  provider: "{{.Values.cloudProvider }}"
  {{- if eq .Values.cloudProvider "azure" }}
  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ .Values.azureConfig.keyVaultName }}"
    objects:  |
      array:
        - |
          objectName: "{{ .Values.azureConfig.hostnameKeyVaultSecretName }}"
          objectType: secret
        - |
          objectName: "{{ .Values.azureConfig.topicKeyVaultSecretName }}"
          objectType: secret
        - |
          objectName: "{{ .Values.azureConfig.connectionStringKeyVaultSecretName }}"
          objectType: secret
    tenantId: "{{ .Values.azureConfig.tenantID }}"
  secretObjects:
    - secretName: "{{ .Values.secretName }}"
      type: Opaque
      data:
        - objectName: "{{ .Values.azureConfig.hostnameKeyVaultSecretName }}"
          key: hostname
        - objectName: "{{ .Values.azureConfig.topicKeyVaultSecretName }}"
          key: topic
        - objectName: "{{ .Values.azureConfig.connectionStringKeyVaultSecretName }}"
          key: connectionstring
  {{- end }}
