global:
  scrapeInterval: "90s"
cluster:
  name: "${cluster_name}"
destinations:
  - name: xenitsweden-prom
    type: prometheus
    url: https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push
    auth:
      type: basic
      username: username
      password: password
    secret:
      create: false
      name: prometheus-grafana-cloud
      namespace: grafana-k8s-monitoring
  - name: xenitsweden-logs
    type: loki
    url: https://logs-prod-025.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: username
      password: password
    secret:
      create: false
      name: loki-grafana-cloud
      namespace: grafana-k8s-monitoring
  - name: xenitsweden-traces
    type: otlp
    url: https://tempo-prod-18-prod-eu-north-0.grafana.net:443
    protocol: grpc
    auth:
      type: basic
      username: username
      password: password
    secret:
      create: false
      name: tempo-grafana-cloud
      namespace: grafana-k8s-monitoring
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
clusterMetrics:
  enabled: true
  kube-state-metrics:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
  opencost:
    enabled: false
  kepler:
    enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  podMonitors:
    enabled: true
    excludeNamespaces: ${grafana_k8s_monitor_config.exclude_namespaces}
  serviceMonitors:
    enabled: true
    excludeNamespaces: ${grafana_k8s_monitor_config.exclude_namespaces}

clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  processors:
    grafanaCloudMetrics:
      enabled: true
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
            - alloy-receiver
alloy-metrics:
  enabled: true
  alloy:
    storagePath: /var/lib/alloy
    mounts:
      extra:
        - name: secret-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
    enableStatefulSetAutoDeletePVC: true
    volumes:
      extra:
        - name: secret-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: grafana-k8s-monitor-secrets

alloy-singleton:
  enabled: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
alloy-logs:
  enabled: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP

crds:
  deploy: true

