{{- if eq .Values.cloudProvider "azure" }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: xenit-proxy
spec:
  type: 0
  resourceID: {{ .Values.azureConfig.resourceID }}
  clientID: {{ .Values.azureConfig.clientID }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: xenit-proxy
spec:
  azureIdentity: xenit-proxy
  selector: xenit-proxy
{{- end }}
