apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: xenit-proxy
  labels:
    name: xenit-proxy
spec:
  provider: "{{.Values.cloudProvider }}"
  {{- if eq .Values.cloudProvider "azure" }}
  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ .Values.azureConfig.keyVaultName }}"
    objects:  |
      array:
        - |
          objectName: "{{ .Values.azureConfig.keyVaultSecretName }}"
          objectType: secret
    tenantId: "{{ .Values.azureConfig.tenantID }}"
  secretObjects:
    - secretName: "{{ .Values.azureConfig.keyVaultSecretName }}"
      type: kubernetes.io/tls
      data:
        - objectName: "{{ .Values.azureConfig.keyVaultSecretName }}"
          key: tls.key
        - objectName: "{{ .Values.azureConfig.keyVaultSecretName }}"
          key: tls.crt
  {{- end }}
  {{- if eq .values.cloudprovider "aws" }}
  parameters:
    objects: |
      - objectName: "{{ .Values.awsConfig.parameterName }}"
        objectType: "ssmparameter"
  #secretObjects:
  #  - secretName: "{{ .Values.keyVaultSecretName }}"
  #    type: kubernetes.io/tls
  #    data:
  #      - objectName: "{{ .Values.keyVaultSecretName }}"
  #        key: tls.key
  #      - objectName: "{{ .Values.keyVaultSecretName }}"
  #        key: tls.crt
  {{- end }}
