apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver
  labels:
    name: thanos-receiver
    app: xenit-proxy
spec:
  selector:
    app: xenit-proxy
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki-api
  labels:
    name: loki-api
    app: xenit-proxy
spec:
  selector:
    app: xenit-proxy
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
