image: grafana/agent:v0.21.2
replicas: 2

environment: ""
clusterName: aks1
cloudProvider: ""

remote:
  logsUrl: ""

azureConfig:
  resourceID: ""
  clientID: ""
  tenantID: ""
  keyVaultName: ""
  keyVaultSecretName: "xenit-proxy-certificate"
