pod:
  user:
    id: 1000
  group:
    id: 1000

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 100m
    memory: 220Mi

monitoring:
  serviceMonitor:
    enabled: false

  grafanaDashboard:
    enabled: false

psp:
  enabled: false

networkpolicy:
  enabled: false
