apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: primary
  namespace: {{ .Release.Namespace }}
  labels:
    agent: grafana-agent-logs
spec:
  clients:
    - url: {{ .Values.remote.logsUrl }}
      externalLabels:
        cluster: {{ .Values.clusterName }}
        environment: {{ .Values.environment }}
      basicAuth:
        username:
          name: {{ .Values.credentialsSecretName }}
          key: logs_username
        password:
          name: {{ .Values.credentialsSecretName }}
          key: logs_password
  podLogsNamespaceSelector:
    matchExpressions:
      - key: "xkf.xenit.io/kind"
        operator: "Exists"
  podLogsSelector:
    matchLabels:
      xkf.xenit.io/monitoring: tenant
