apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent-traces
  name: grafana-agent-traces
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: agent-http-metrics
      port: 8080
      targetPort: 8080
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: otlp-http
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: otlp-grpc
    - name: otlp-legacy
      port: 55681
      protocol: TCP
      targetPort: otlp-legacy
    - name: jaeger
      port: 55678
      protocol: TCP
      targetPort: jaeger
  selector:
    name: grafana-agent-traces
