# Default values for azure-metrics-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: webdevops/azure-metrics-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "22.3.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 15m
    memory: 25Mi

nodeSelector: {}

tolerations: []

affinity: {}

aadpodidbinding:
  name: azure-metrics
  enabled: true

podmonitor:
  loadBalancer: true
  kubernetes: true

subscription: ""
