{{- if .Values.prometheusEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: helm-controller
  labels:
    xkf.xenit.io/monitoring: platform
spec:
  selector:
    matchLabels:
      app: helm-controller
  podMetricsEndpoints:
    - port: http-prom
{{- end }}
