on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.GH_ACTION_APP_ID }}
          private_key: ${{ secrets.GH_ACTION_APP_PRIVATE_KEY }}

      - name: Workflow dispatch xkf-templates
        id: dispatch
        env:
          VERSION: ${{ inputs.version }}
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          set -x
          VERSION=${GITHUB_REF#refs/*/}
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/XenitAB/xkf-templates/actions/workflows/upgrade.yaml/dispatches \
            -d '{"ref":"main","inputs":{"version": "'"$VERSION"'"}}'
